INSERT INTO public.resources (title, description, url, type, category, provider, is_free, rating) VALUES
('CS50: Introduction to Computer Science','Harvard''s legendary intro CS course covering C, Python, SQL, and web dev.','https://cs50.harvard.edu/','course','Computer Science','Harvard / edX',true,4.9),
('freeCodeCamp Full Stack Curriculum','Interactive lessons covering HTML, CSS, JS, React, Node, and databases.','https://www.freecodecamp.org/','course','Full Stack','freeCodeCamp',true,4.8),
('The Odin Project','Full-stack open-source curriculum with Ruby and JavaScript paths.','https://www.theodinproject.com/','course','Full Stack','The Odin Project',true,4.7),
('MIT 6.006 Introduction to Algorithms','Classic algorithms course with video lectures and problem sets.','https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/','course','Data Structures & Algorithms','MIT OCW',true,4.8),
('NeetCode 150','Curated list of 150 LeetCode problems grouped by pattern for interview prep.','https://neetcode.io/','guide','Interview Prep','NeetCode',true,4.9),
('Striver''s A2Z DSA Sheet','Comprehensive DSA sheet with 450+ problems organized by topic.','https://takeuforward.org/strivers-a2z-dsa-course/sheet','guide','Data Structures & Algorithms','takeUforward',true,4.8),
('System Design Primer','Learn how to design large-scale systems — prep for system design interviews.','https://github.com/donnemartin/system-design-primer','guide','System Design','Donne Martin',true,4.7),
('Roadmap.sh','Community-driven roadmaps for frontend, backend, DevOps, and more.','https://roadmap.sh/','guide','Career Planning','roadmap.sh',true,4.6),
('JavaScript.info','The modern JavaScript tutorial — from basics to advanced topics.','https://javascript.info/','guide','JavaScript','javascript.info',true,4.7),
('Full Stack Open','Deep dive into modern web dev with React, Node, GraphQL, and TypeScript.','https://fullstackopen.com/','course','Full Stack','University of Helsinki',true,4.8),
('Scrimba Frontend Developer Path','Interactive screencasts for learning HTML, CSS, JS, and React.','https://scrimba.com/learn/frontend','course','Frontend','Scrimba',false,4.5),
('Python for Everybody','Beginner-friendly Python course covering data structures and web scraping.','https://www.py4e.com/','course','Python','Dr. Chuck',true,4.7),
('Fast.ai Practical Deep Learning','Hands-on deep learning course — top-down approach, no PhD required.','https://course.fast.ai/','course','Machine Learning','fast.ai',true,4.8),
('Andrew Ng Machine Learning Specialization','Gold-standard ML course covering supervised, unsupervised, and best practices.','https://www.coursera.org/specializations/machine-learning-introduction','course','Machine Learning','Stanford / Coursera',false,4.9),
('Google Data Analytics Certificate','Professional certificate covering spreadsheets, SQL, R, and Tableau.','https://www.coursera.org/professional-certificates/google-data-analytics','course','Data Science','Google / Coursera',false,4.6),
('LeetCode','Platform for coding interview practice with thousands of problems.','https://leetcode.com/','project','Interview Prep','LeetCode',true,4.7),
('HackerRank','Coding challenges and competitions across multiple domains.','https://www.hackerrank.com/','project','Interview Prep','HackerRank',true,4.4),
('Codeforces','Competitive programming platform with regular contests.','https://codeforces.com/','project','Competitive Programming','Codeforces',true,4.6),
('Kaggle Learn','Micro-courses on Python, ML, SQL, and data visualization with hands-on notebooks.','https://www.kaggle.com/learn','course','Data Science','Kaggle',true,4.5),
('Git & GitHub Crash Course','Traversy Media video tutorial on version control fundamentals.','https://www.youtube.com/watch?v=SWYqp7iY_Tc','video','Git & DevOps','Traversy Media',true,4.5),
('Docker for Beginners','TechWorld with Nana''s comprehensive Docker tutorial.','https://www.youtube.com/watch?v=3c-iBn73dDE','video','DevOps','TechWorld with Nana',true,4.6),
('AWS Cloud Practitioner Essentials','Free AWS training for cloud fundamentals and certification prep.','https://aws.amazon.com/training/digital/aws-cloud-practitioner-essentials/','course','Cloud Computing','AWS',true,4.5),
('Fireship YouTube Channel','Fast-paced tech explainers and 100-second concept breakdowns.','https://www.youtube.com/@Fireship','video','General Tech','Fireship',true,4.7),
('Tech Interview Handbook','Curated guide covering resume, algorithms, system design, and behavioral interviews.','https://www.techinterviewhandbook.org/','guide','Interview Prep','Yangshun Tay',true,4.8),
('Pramp','Free peer-to-peer mock interview platform for coding and system design.','https://www.pramp.com/','project','Interview Prep','Pramp',true,4.4),
('Eloquent JavaScript','Free online book covering JS fundamentals, DOM, Node, and more.','https://eloquentjavascript.net/','article','JavaScript','Marijn Haverbeke',true,4.6),
('MDN Web Docs','Comprehensive reference for HTML, CSS, and JavaScript.','https://developer.mozilla.org/','article','Web Development','Mozilla',true,4.8),
('React Official Tutorial','Learn React with the official step-by-step tutorial.','https://react.dev/learn','guide','React','Meta',true,4.7),
('Tailwind CSS Documentation','Utility-first CSS framework docs with examples.','https://tailwindcss.com/docs','guide','CSS','Tailwind Labs',true,4.6),
('TypeScript Handbook','Official guide to learning TypeScript from basics to advanced.','https://www.typescriptlang.org/docs/handbook/','guide','TypeScript','Microsoft',true,4.5),
('SQL Bolt','Interactive SQL lessons from beginner to advanced queries.','https://sqlbolt.com/','course','Databases','SQLBolt',true,4.6),
('MongoDB University','Free courses on MongoDB, aggregation, and data modeling.','https://university.mongodb.com/','course','Databases','MongoDB',true,4.4),
('GFG Interview Preparation','GeeksforGeeks interview prep articles and practice problems.','https://www.geeksforgeeks.org/company-interview-corner/','article','Interview Prep','GeeksforGeeks',true,4.5),
('Building Microservices by Sam Newman','Essential reading on microservice architecture patterns.','https://samnewman.io/books/building_microservices_2nd_edition/','article','System Design','Sam Newman',false,4.6),
('Designing Data-Intensive Applications','Deep dive into distributed systems, databases, and data pipelines.','https://dataintensive.net/','article','System Design','Martin Kleppmann',false,4.9),
('GitHub Student Developer Pack','Free tools, credits, and resources for student developers.','https://education.github.com/pack','guide','Career Planning','GitHub',true,4.7),
('LinkedIn Learning','Professional courses on business, tech, and creative skills.','https://www.linkedin.com/learning/','course','General Tech','LinkedIn',false,4.3),
('Coursera GRE Prep','GRE preparation resources for higher studies aspirants.','https://www.coursera.org/courses?query=gre','course','Higher Studies','Coursera',false,4.2),
('IELTS Preparation by British Council','Free IELTS prep materials for study abroad applications.','https://www.britishcouncil.org/exam/ielts/preparation','guide','Higher Studies','British Council',true,4.4),
('How to Write a Statement of Purpose','Guide to crafting compelling SOPs for grad school applications.','https://grad.berkeley.edu/admissions/apply/statement-purpose/','article','Higher Studies','UC Berkeley',true,4.5),
('Resume Worded','AI-powered resume and LinkedIn profile optimization tool.','https://resumeworded.com/','project','Career Planning','Resume Worded',false,4.3),
('Harvard CS50 Web Programming','Follow-up to CS50 covering Django, JavaScript, SQL, and scalability.','https://cs50.harvard.edu/web/','course','Web Development','Harvard',true,4.7),
('Exercism','Free coding exercises with mentor feedback in 60+ languages.','https://exercism.org/','project','Programming Practice','Exercism',true,4.5),
('Frontend Mentor','Real-world frontend challenges with professional designs.','https://www.frontendmentor.io/','project','Frontend','Frontend Mentor',true,4.6),
('Figma for Developers','Learn UI/UX design basics using Figma — essential for full-stack devs.','https://www.figma.com/resources/learn-design/','video','UI/UX Design','Figma',true,4.4)
