// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjrisantkuoluwzjmiqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqcmlzYW50a3VvbHV3emptaXFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQwNjEwOTMsImV4cCI6MjA4OTYzNzA5M30.oaf4abR94BEMKRRyG7pAXdo2qNf9tBk8A-RP_e8azko";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});